FROM ubuntu:22.04
RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install python3 -y && apt-get install openjdk-11-jdk -y && apt-get install openjdk-11-jre -y
RUN java -version
RUN echo "Hello Docker"

EXPOSE 8080